version: 0.2

phases:
  install:
    commands:
      - cd db_api
      - ./deploy.sh -i
  build:
    commands:
      - ./deploy.sh -b

artifacts:
  files:
    - db_api/packaged-template.yaml
  name: PackagedTemplate
